import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import "react-modern-drawer/dist/index.css";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head></head>
      <body className="p-[24px]">
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
