import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import Menu from "@/components/menu";
import "react-modern-drawer/dist/index.css";
import { Providers } from "./providers";
import "react-responsive-modal/styles.css";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session: any = await getServerSession(authOptions);
  return (
    <html lang="en" suppressHydrationWarning>
      <head></head>
      <body>
        <Providers session={session}>
          <Header />
          <main className="px-[24px] py-[32px] flex-1 overflow-auto">
            {children}
            <ToastContainer
              closeButton={false}
              hideProgressBar
              position="top-center"
              rtl
            />
          </main>
          <Menu />
        </Providers>
      </body>
    </html>
  );
}
